Correct yaml indentation in GH actions config

diff --git a/.github/workflows/ansible_test.yml b/.github/workflows/ansible_test.yml
--- a/.github/workflows/ansible_test.yml
+++ b/.github/workflows/ansible_test.yml
@@ -8,40 +8,40 @@ jobs:
     runs-on: ubuntu-latest
     steps:
 
-    - name: Checkout code from Github
-      uses: actions/checkout@v2
+      - name: Checkout code from Github
+        uses: actions/checkout@v2
 
-    - name: Set up Python 3.8
-      uses: actions/setup-python@v1
-      with:
-        python-version: 3.8
+      - name: Set up Python 3.8
+        uses: actions/setup-python@v1
+        with:
+          python-version: 3.8
 
-    - name: Install latest Ansible through pip
-      run: pip install ansible
+      - name: Install latest Ansible through pip
+        run: pip install ansible
 
-    - name: Output python and ansible versions
-      run: |
-        python --version
-        ansible --version
+      - name: Output python and ansible versions
+        run: |
+          python --version
+          ansible --version
 
-    - name: Create ansible.cfg with correct roles_path
-      run: printf '[defaults]\nroles_path=../' > ansible.cfg
+      - name: Create ansible.cfg with correct roles_path
+        run: printf '[defaults]\nroles_path=../' > ansible.cfg
 
-    - name: Basic Ansible role syntax check
-      run: ansible-playbook -i tests/inventory --syntax-check tests/test.yml
+      - name: Basic Ansible role syntax check
+        run: ansible-playbook -i tests/inventory --syntax-check tests/test.yml
 
-    - name: Real Ansible run
-      run: ansible-playbook -i tests/inventory tests/test.yml
+      - name: Real Ansible run
+        run: ansible-playbook -i tests/inventory tests/test.yml
 
-    - name: Second run to check for indempotence
-      run: "ansible-playbook -i tests/inventory tests/test.yml | grep -q 'changed=0.*failed=0' && (echo 'Idempotence test: pass' && exit 0) || (echo 'Idempotence test: fail' && exit 1)"
+      - name: Second run to check for indempotence
+        run: "ansible-playbook -i tests/inventory tests/test.yml | grep -q 'changed=0.*failed=0' && (echo 'Idempotence test: pass' && exit 0) || (echo 'Idempotence test: fail' && exit 1)"
 
-    - name: Setup serverspec (install gem)
-      run: sudo gem install serverspec
+      - name: Setup serverspec (install gem)
+        run: sudo gem install serverspec
 
-    - name: Run serverspec (as root to see all files)
-      run: sudo rake spec
+      - name: Run serverspec (as root to see all files)
+        run: sudo rake spec
 
-    - name: Ouput filebeat config for debugging
-      run: sudo cat /etc/filebeat/filebeat.yml
+      - name: Ouput filebeat config for debugging
+        run: sudo cat /etc/filebeat/filebeat.yml
 
